### ISSUE TITLE
Can't access resources in other namespaces

### ISSUE THREAD

**Issue by jtama** [quarkiverse/quarkus-operator-sdk#177]
Hi,
I am not sure if the issue is an extension or fabric8 client issue.

I am using quarkus-operator-sdk:2.0.2. The operator is deployed is a K8S cluster in a dedicated namespace. 

ClusterRoler and ClusterRoleBinding are defined as follow : 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: [ "" ]
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: operator-account
    namespace: lemur-dev
---
```

When trying to access an other namespace I get the following error : 

```bash
2021-12-21 15:52:05,899 ERROR [com.one.yap.ri.RandomInvasionController] (EventHandler-randominvasioncontroller) Error querying API: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.3.0.1/api/v1/namespaces/yap-dev. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces "test-dev" is forbidden: User "system:serviceaccount:lemure-dev:operator-account" cannot get resource "namespaces" in API group "" in the namespace "test-dev".
```

I am a bit confused, as namespace are not scoped, and if I try directly from sh I get : 

```bash
kubectl auth can-i get namespace --as=system:serviceaccount:lemure-dev:operator-account
Warning: resource 'namespaces' is not namespace scoped
yes
```

Am I missing something ?

**Comment by scrocquesel** [comment]
```
subjects:
  - kind: ServiceAccount
    name: operator-account
    namespace: lemur-dev
```
shouldn't it be `lemure-dev ` with an e before dash ?
