### ISSUE TITLE
Generated ClusterRoleBinding doesn't have subjects.namespace defined

### ISSUE THREAD

**Issue by andreaTP** [quarkiverse/quarkus-operator-sdk#187]
A default Controller generates the an invalid related `ClusterRoleBinding`.

e.g.:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: realmcontroller-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: realmcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
```

This is not applicable to Kubernetes and it fails with:

```
The ClusterRoleBinding "realmcontroller-cluster-role-binding" is invalid: subjects[0].namespace: Required value
```
since the `namespace` is a mandatory field.
