### ISSUE TITLE
Rename the extension `quarkus-operator-sdk-csv-generator` to `quarkus-operator-sdk-bundle-generator`

### ISSUE THREAD

**Issue by Sgitario** [quarkiverse/quarkus-operator-sdk#243]
Follow-up action by https://github.com/quarkiverse/quarkus-operator-sdk/pull/238

Instead of generating only the CSV manifests at `target/manifests`, this extension should generate the bundle at `target/bundle` folder with the following content:
- `manifests`: same content as before at `target/manifests`
- `metadata/annotations.yaml`: with some default annotations and allow to add some more annotations via configuration. Example:
```yaml
annotations:
  operators.operatorframework.io.bundle.channel.default.v1: alpha
  operators.operatorframework.io.bundle.channels.v1: alpha
  operators.operatorframework.io.bundle.manifests.v1: manifests/
  operators.operatorframework.io.bundle.mediatype.v1: registry+v1
  operators.operatorframework.io.bundle.metadata.v1: metadata/
  operators.operatorframework.io.bundle.package.v1: joke-operator
```

- `bundle.Dockerfile`: to generate the bundle image. Content:
```
FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=joke-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha

COPY manifests /manifests/
COPY metadata /metadata/
```

With these changes, it would not be necessary to call `opm alpha bundle generate` any longer (document and workflow build action should be updated accordingly).
