### ISSUE TITLE
feat: Allow declare custom rules in RBAC

### ISSUE THREAD

**Issue by philippart-s** [quarkiverse/quarkus-operator-sdk#263]
Hi,

Perhaps I've missed the information but I need, with my operator, to create a service and to do this the service account must have this rule:

```yaml
  - apiGroups:
    - ""
    resources:
    - services
    - serviceaccounts
    verbs:
    - "*"      
```

It would be cool if the extension would allow to add this kind of custom rules configuration.
