### ISSUE TITLE
Crds get mangled between modules

### ISSUE THREAD

**Issue by shawkins** [quarkiverse/quarkus-operator-sdk#31]
We have a multi-module project where the api module contains 2 crds getting generated with fabric8 crd-generator version 5.1.1.  The yamls in taget/classes/META-INF/fabric8 look correct.

In an operator module we are using the crds with the 1.8.2 quarkus operator sdk and corresponding quarkus 1.13.1 versions.  In the operator/target/kubernetes folder it contains copies of the yaml files that are generated from the api module.  However the files have significant differences.

Among other changes, the scope has been modified.  In the api (correct) yaml we have:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: somename
spec:
  ...
  scope: Namespaced
```
In the operator yaml we have:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: somename
spec:
  ...
  scope: Cluster
```
Because we have existing tests that were installing the crds from the original location, as well as all yaml from the operator kubernetes file, we got errors complaining about an invalid change of the spec.scope field.

Much of the rest of the yaml has changes as well, I can summarize that if needed.
