### ISSUE TITLE
How to disable automatic CRD installation on dev launch

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [quarkiverse/quarkus-operator-sdk#511]
Hi, I have a CRD defined in yaml (or more specifically, I use helm to install CRD to kubernetes cluster).

The generated CRD overrides the one that I applied - is it possible to disable CRD installation when running `quarkusDev`? In development mode it seems like CRD is always installed, no matter what configuration is provided.

It looks like this configuration is not used:
```yaml
# application.yml
quarkus:
  operator-sdk:
    crd:
      apply: false
```
I injected `BuildTimeOperatorConfiguration` and saw that `crd.apply` is empty 🤔
