### ISSUE TITLE
Operators do not work with OLM all namespaces mode

### ISSUE THREAD

**Issue by Jamstah** [quarkiverse/quarkus-operator-sdk#656]
When using OLM, OLM will provide a pod annotation for the operator listing the namespaces the operator should watch. Typically, this is passed to the container as an environment variable by using the downward API.

OLM will put a comma separated list of namespaces into the annotation, reserving the empty string `""` as an indicator to mean "All namespaces on the cluster".

With a QOSDK operator, we use the `QUARKUS_OPERATOR_SDK_NAMESPACES` to configure the namespaces the operator should watch based on the annotation set by OLM, which will be `""` for all namespaces mode. This runtime configuration does not override any configuration set at build time, perhaps because the empty string is not picked up by quarkus, to be determined.

This means that the QOSDK does not work with OLM all namespaces mode when the operator is built with the `quarkus.operator-sdk.controllers.keycloakcontroller.generate-with-watched-namespaces` build time property, because the empty string does not override the setting correctly.

**Comment by metacosm** [comment]
Hmm, not sure this will actually be fixable easily because I'm not sure we will have a way to distinguish between OLM configuring things for cluster-level or a user omission…

**Comment by metacosm** [comment]
How is the OLM value passed to QOSDK in this scenario? You mention an annotation, how does that work exactly?

**Comment by Jamstah** [comment]
Doing a test, this code returns false if the ENV VAR is set to the empty string:

```
runTimeConfiguration.namespaces.isPresent()
```

That may be a quarkus bug.

**Comment by Jamstah** [comment]
The annotation gets passed with the downward API:

```
                      - name: QUARKUS_OPERATOR_SDK_NAMESPACES
                        valueFrom:
                          fieldRef:
                            fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
```
