### ISSUE TITLE
Helm Chart generation ignores (some?) objects from src/kubernetes/kubernetes.yaml

### ISSUE THREAD

**Issue by jcechace** [quarkiverse/quarkus-operator-sdk#754]
In our case we define additional ClusterRole and RoleBinding in our custom kubernetes.yaml

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-view
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debezium-operator-config-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: config-view
subjects:
  - kind: ServiceAccount
    name: debezium-operator
```

However these seem to be compeltely ingored by Helm Chart generation. Obviously this is a problem. 

// cc @csviri
