### ISSUE TITLE
Helm chart generation incorrectly filters resources from kubernetes.yaml

### ISSUE THREAD

**Issue by jcechace** [quarkiverse/quarkus-operator-sdk#801]
`HelmChartProcessor` seems to rely on `ApplicationInfoBuildItem` for quite a few value. For example here 

https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java#L158

However I don't think that  `ApplicationInfoBuildItem#name` is the expected value here. In my opinion the correct value is  the one set to  `quarkus.kubernetes.name` (and `quarkus.kubernetes.version` for version respectively). The `quarkus.kubernetes.name` property actually defaults to application name. 

The obvious workaround is to also set `quarkus.application.name`.  However when setting both 

`quarkus.application.name=debezium-operator` and
`quarkus.kubernetes.name=debezium-operator` 

together with the following `src/kubernetes/kubernetes.yml`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-view
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debezium-operator-config-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: config-view
subjects:
  - kind: ServiceAccount
    name: debezium-operator
```

Resulted in no `kubernetes.yml` being generated in the chart's templates directory. Maybe I'm missing something but the filtering logic should let these through
