### ISSUE TITLE
[Question]: How to disable Probes, e.g. livenessProbe?

### ISSUE THREAD

**Issue by Jeansen** [quarkiverse/quarkus-operator-sdk#818]
I have the need to disable probes. But nothing so far worked. I was able to overwrite settings, e.g. the initial delay, but the quarkus kubernetes extensions does not offer any options and the smallrye-health options for disabling that extension did not work either. Every time I have all probes with some defaults set in the generated kubernetes.yml, for example
```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

So, my questions is, how do I disable this? I am aware, this is not directly specific to the QOSDK extension, but since these two extensions are a dependency, I thought, I start here. Maybe I am just blind in the tunnel .....
