### ISSUE TITLE
Helm chart generation sets {{ .Values.version }} based on container tag rather than app version 

### ISSUE THREAD

**Issue by jcechace** [quarkiverse/quarkus-operator-sdk#821]
https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java#L225

This leads to strange values generated for quarkus k8 labels as templates are defined with 

```yaml
labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/managed-by: quarkus
```

I'd actually argue that unless this "version" is supposed to configure deployment image tag (in which case it should be called "imageTag" or sth), then this template should reference {{ .Chart.appVersion }} instead. Which would mean that ` {{ .Values.version }} `` is actually redundant .
