### ISSUE TITLE
Watch environment variables are generated incorrectly in OLM bundle

### ISSUE THREAD

**Issue by jcechace** [quarkiverse/quarkus-operator-sdk#855]
The following duplicity gets generated in OLM CSV

```yaml
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_DEBEZIUMSERVER_NAMESPACES
                  value: "{watchNamespaces}"
                - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_DEBEZIUMSERVER_NAMESPACES
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.annotations['olm.targetNamespaces']"
```

The problem exists at minimum since 6.6.3
